config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#home'
  get '/epick', to: 'emails#upload'
  post '/emails', to: 'emails#emails'
  get '/dmpick', to: 'direct_mails#dm_merge_variables_pick'
  get '/emails', to: 'emails#emails'
  get '/directmails', to: 'direct_mails#direct_mail'
  get '/clearemails', to: 'emails#clear'
  get '/select', to: 'emails#select'
  get '/spellcheck', to: 'emails#spellcheck'
  post '/display_mvs', to: 'emails#email_merge_variables_pick'
  resources :emails

end

app/views/layouts/_MV_multiple_variables.html.erb
<p>this is the multiple variables one</p>

<table class="table1">
  <% @merge_variable.each_with_index do |variable, index| %>
     <tr>
       <form class="form-inline">
       <% @merge_variable[index].each do |variable|  %>
         <% if index == 0 %>
          <th>
            <input type="checkbox" id="thing"></input>
              <input type="text" class="form-control mb-2 mr-sm-2 mb-sm-0" id="inlineFormInput" value="<%= variable %>"></input>
           </th>
         <% else %>
           <td>
               <input type="text" class="form-control mb-2 mr-sm-2 mb-sm-0" id="inlineFormInput" value="<%= variable %>"></input>
           </td>
         <% end %>
       <% end %>
       </form>
     </tr>
   <% end %>
   </table>

app/views/layouts/_MV_single_variable.html.erb
  <p> this is the single one</p>
<%= form_tag('/emails', class: "form-inline", method: "post") do -%>
<table class="table1">
  <div class="stuff">
  <% @merge_variable.first.each_with_index do |variable, index| %>
     <tr>

         <% if index == 0 %>
           <th>
             <%= check_box_tag "thing" %>
             <%= text_field_tag "mv_header[]", variable%>
           </th>
         <% else %>
           <td>
             <%= text_field_tag "mv_data[]",variable%>
           </td>
         <% end %>
     </tr>
   <% end %>

     </div>
   </table>
   <%= submit_tag "Look at Emails"%>
<% end %>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <!-- <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <% if current_page?(root_path) %>
                    <%= link_to "Email", epick_path, :method => :get, class: "btn btn-danger btn-lg" %>
                    <%= link_to "Direct Mail", directmails_path, class: "btn btn-primary btn-lg"%>
                <% end %>
            </div>
        </div>
    </div> -->
</footer>

app/views/layouts/_message.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= value %>
   </div>
<% end %>

app/views/layouts/_more_table_field.html.erb
<td><%= text_field_tag 'mv_data[]',variable%></td>

app/views/layouts/_navigation.html.erb
<!-- <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <%= link_to "Clear", clearemails_path, class: "back" %>
    </ul>
  </div>
</nav> -->

app/views/layouts/_navigation_links.html.erb
<!-- <%# add navigation links to this file %>
<li>
    <%= link_to 'Home', root_path %>
</li>
<li>
    <%= link_to 'Email QA', 'uploads_path' %>
</li>
<li>
    <%= link_to 'Direct Mail', 'uploads_path' %>
</li> -->

app/views/layouts/_render_emails.html.erb
<div class="button_container">
<%= link_to "Clear", clearemails_path, class: "button clear" %>
<%= link_to "Spell Check", spellcheck_path(:id => @email.id), :class=>"spell" %>
<% @all_emails.each do |email| %>
<%= link_to "#{email.version}", select_path(:id => email.id), :class=>"button" %>
<% end %>
</div>

<div class="container down">
  <div class="row">
    <div class="col-sm">
      <!-- start email -->
        <div class="email">
          <div class="horizontally_align_results">
            <label for="from">From:</label>
            <p id="from"><%= @email.from %></p>
            <div class=""></div>
            <textarea class="from text" rows="1" id="from"><%= @email.from %></textarea>
          </div>

          <div class="horizontally_align_results">
            <div class="form-group">
              <label for="subject">Subject:</label>
              <textarea class="subject text" rows="1" id="subject"><%= @email.subject %></textarea>
            </div>
          </div>

          <div class="horizontally_align_results">
            <div class="form-group">
              <label for="header">Header:</label>
              <% @email.header.each do |sentance| %>
              <textarea class="header text" rows="1" id="header"><%= sentance %></textarea>
              <% end %>
            </div>
          </div>

          <div class="horizontally_align_results">
            <div class="form-group">
              <label for="body">Body:</label>
              <% @email.body.each do |sentance| %>
              <textarea class="body text" rows="1" id="body"><%= sentance %></textarea>
              <% end %>
            </div>
          </div>

          <div class="horizontally_align_results">
            <div class="form-group">
              <label for="footer">Footer:</label>
              <% @email.footer.each do |sentance| %>
              <textarea class="footer text" rows="1" id="footer"><%= sentance %></textarea>
              <% end %>
            </div>
          </div>
          </div>
          <p class="versioning">Email should be getting the:  <%= @email.version %> version. </p>
          <iframe src="https://drive.google.com/file/d/<%= @email.qa_list_data["image"]%>/preview" width="500" height="700"></iframe>
          <!-- end email -->
          <% if @versions_not_preset %>
            <% unless @versions_not_preset.empty? %>
              <p>Versions missing are:
              <% @versions_not_preset.each do |version, v| %>
              <br>
              <%= version %>
              <% end %>
              </p>
            <% end %>
          <% end %>


    </div>
    <div class="col-sm">
      <!-- start pg -->
      <div class="col-sm">
        <div class="pg">
        <div class="horizontally_align_results">
          <label for="pgfrom">From:</label><br />
          <div id="pgfrom" class="pgfrom">
            <p>
            <% if @email.qa_list_data["from"] %>
              <% @email.qa_list_data["from"].each do |row| %>
                <%= row.cell_value %>
              <% end %>
            <% end %>
            </p>
          </div>
        </div>

        <div class="horizontally_align_results">
          <label for="pgsubject">Subject:</label><br />
          <div id="pgsubject" class="pgsubject">
            <p>
            <% if @email.qa_list_data["subject"] %>
              <% @email.qa_list_data["subject"].each do |row| %>
                <%= row.cell_value %>
                <% end %>
              <% end %>
            </p>
          </div>
        </div>


        <label for="pgbody">Body:</label><br />

        <div id="pgbody" class="pgbody">

        <% @email.qa_list_data["body"].each do |k,v| %>
          <div class="part_body" id="part_body">
            <% v.each do |match| %>
              <%= match.value %>
            <% end %>
          </div>
        <% end %>

      </div>
      <!-- end pg -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Quality Assistance" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Quality Assistance" %>">
    <%= favicon_link_tag 'favicon.png' %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <!-- Custom Fonts -->
    <!-- <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css"> -->
    <!-- <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css"> -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>


  </head>
  <body>
      <%= render 'layouts/navigation' %>
      <%= render 'layouts/message' %>
      <%= yield %>
      <%= render 'layouts/footer' %>

  </body>
</html>